-- ============================================================================
-- SACCOLink - Credit Passport System
-- FULL INSTALL SCRIPT  (single file deliverable)
--
-- Recreates the complete schema, PL/SQL, sample data and multi-user layer.
-- Run as the SACCOLINK schema user on a fresh Oracle Database XE:
--     sqlplus SACCOLINK/sacco123@//localhost:1521/XEPDB1 @saccolink_install.sql
--
-- One-time sysdba setup required before this script (see README):
--     CREATE USER SACCOLINK IDENTIFIED BY sacco123;
--     GRANT CONNECT, RESOURCE TO SACCOLINK;
--     GRANT CREATE ANY CONTEXT, CREATE ANY VIEW, CREATE SYNONYM TO SACCOLINK;
--
-- Parts included (in run order):
--   01_schema.sql       tables, constraints, sequences, indexes, view, synonyms
--   02_plsql.sql        scoring / passport / verification routines
--   04_triggers.sql     PK + QR-token + consent-audit triggers
--   05_packages.sql     PKG_SACCOINK, PKG_SACCOINK_REPORT (explicit cursor)
--   03_sample_data.sql  7 members, loans, savings, scores, passports
--   06_multiuser.sql    APP_USER + LOAN_REQUEST, SP_LOGIN, V_MY_* views
--   07_queries.sql      Part IV/V demo queries (WHERE/GROUP BY/HAVING/joins/
--                       subqueries/set ops/views + explicit cursor)
-- ============================================================================

-- ====================================================================
-- >>> 01_schema.sql
-- ====================================================================
-- ============================================================================
-- SACCOLink
-- Schema Definition -- 5 entities
-- Oracle Database 18c XE | Java Swing (JDBC)
-- ============================================================================
-- Entities:
--   1. MEMBER          - registered member (NIN anchored)
--   2. LOAN_RECORD     - loan history per member
--   3. SAVINGS_RECORD  - monthly savings per member
--   4. CREDIT_SCORE    - computed score per member
--   5. CREDIT_PASSPORT - time-limited shareable credit summary
--
-- Primary keys are NUMBER columns populated by sequences + BEFORE INSERT
-- triggers (see sql/04_triggers.sql). This is the classic Oracle pattern:
-- no GENERATED BY DEFAULT AS IDENTITY columns.
-- ============================================================================

-- Tolerant "drop everything owned by this schema" block, so the combined
-- install script runs cleanly on a brand-new (empty) Oracle XE schema too.
DECLARE
    TYPE t_names IS TABLE OF VARCHAR2(128);
    TYPE t_obj  IS RECORD (nm VARCHAR2(128), tp VARCHAR2(30));
    TYPE t_objs IS TABLE OF t_obj;
    v_items t_names;
    v_objs  t_objs;
BEGIN
    SELECT table_name   BULK COLLECT INTO v_items FROM user_tables;
    FOR i IN 1 .. v_items.COUNT LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || v_items(i) || '" CASCADE CONSTRAINTS';
    END LOOP;
    SELECT sequence_name BULK COLLECT INTO v_items FROM user_sequences
     WHERE sequence_name NOT LIKE 'ISEQ$$%';   -- system-generated, undroppable
    FOR i IN 1 .. v_items.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP SEQUENCE "' || v_items(i) || '"';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    SELECT view_name    BULK COLLECT INTO v_items FROM user_views;
    FOR i IN 1 .. v_items.COUNT LOOP
        EXECUTE IMMEDIATE 'DROP VIEW "' || v_items(i) || '"';
    END LOOP;
    SELECT synonym_name BULK COLLECT INTO v_items FROM user_synonyms;
    FOR i IN 1 .. v_items.COUNT LOOP
        EXECUTE IMMEDIATE 'DROP SYNONYM "' || v_items(i) || '"';
    END LOOP;
    SELECT object_name, object_type BULK COLLECT INTO v_objs
      FROM user_objects
     WHERE object_type IN ('PACKAGE', 'PACKAGE BODY', 'PROCEDURE', 'FUNCTION');
    FOR i IN 1 .. v_objs.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP ' || v_objs(i).tp || ' "' || v_objs(i).nm || '"';
        EXCEPTION
            WHEN OTHERS THEN NULL;  -- body may already be dropped with its package
        END;
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- Sequences (consumed by the BEFORE INSERT triggers in 04_triggers.sql)
-- ----------------------------------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOAN     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SAVINGS  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SCORE    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PASSPORT START WITH 1 INCREMENT BY 1 NOCACHE;

-- ----------------------------------------------------------------------------
-- 1. MEMBER
-- ----------------------------------------------------------------------------
CREATE TABLE MEMBER (
    MEMBER_ID       NUMBER       NOT NULL
                    CONSTRAINT PK_MEMBER PRIMARY KEY,
    NIN             VARCHAR2(14) NOT NULL
                    CONSTRAINT UQ_MEMBER_NIN UNIQUE,
    FULL_NAME       VARCHAR2(200) NOT NULL,
    PHONE_NUMBER    VARCHAR2(15)  NOT NULL
                    CONSTRAINT UQ_MEMBER_PHONE UNIQUE,
    DISTRICT        VARCHAR2(100) NOT NULL,
    CONSENT_GIVEN   CHAR(1)       DEFAULT 'N'
                    CONSTRAINT CK_MEMBER_CONSENT CHECK (CONSENT_GIVEN IN ('Y','N')),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_MEMBER_NIN
        CHECK (REGEXP_LIKE(NIN, '^[A-Z0-9]{14}$'))
);

-- ----------------------------------------------------------------------------
-- 2. LOAN_RECORD
-- ----------------------------------------------------------------------------
CREATE TABLE LOAN_RECORD (
    LOAN_ID           NUMBER       NOT NULL
                      CONSTRAINT PK_LOAN PRIMARY KEY,
    MEMBER_ID         NUMBER       NOT NULL
                      CONSTRAINT FK_LOAN_MEMBER REFERENCES MEMBER(MEMBER_ID),
    LOAN_AMOUNT       NUMBER(15,2) NOT NULL,
    DISBURSEMENT_DATE DATE         NOT NULL,
    REPAYMENT_DATE    DATE,
    LOAN_STATUS       VARCHAR2(20) NOT NULL
                      CONSTRAINT CK_LOAN_STATUS
                      CHECK (LOAN_STATUS IN ('ACTIVE','REPAID','DEFAULTED'))
);

CREATE INDEX IDX_LOAN_MEMBER ON LOAN_RECORD(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- 3. SAVINGS_RECORD
-- ----------------------------------------------------------------------------
CREATE TABLE SAVINGS_RECORD (
    SAVINGS_ID          NUMBER       NOT NULL
                        CONSTRAINT PK_SAVINGS PRIMARY KEY,
    MEMBER_ID           NUMBER       NOT NULL
                        CONSTRAINT FK_SAVINGS_MEMBER REFERENCES MEMBER(MEMBER_ID),
    CONTRIBUTION_MONTH  DATE         NOT NULL,
    AMOUNT_CONTRIBUTED  NUMBER(12,2) NOT NULL,
    CONSTRAINT CK_SAVINGS_MONTH
        CHECK (CONTRIBUTION_MONTH = TRUNC(CONTRIBUTION_MONTH, 'MM')),
    CONSTRAINT UQ_SAVINGS_MEMBER_MONTH
        UNIQUE (MEMBER_ID, CONTRIBUTION_MONTH)
);

CREATE INDEX IDX_SAVINGS_MEMBER ON SAVINGS_RECORD(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- 4. CREDIT_SCORE
-- ----------------------------------------------------------------------------
CREATE TABLE CREDIT_SCORE (
    SCORE_ID        NUMBER      NOT NULL
                    CONSTRAINT PK_SCORE PRIMARY KEY,
    MEMBER_ID       NUMBER      NOT NULL
                    CONSTRAINT FK_SCORE_MEMBER REFERENCES MEMBER(MEMBER_ID),
    SCORE_VALUE     NUMBER(5,2) NOT NULL
                    CONSTRAINT CK_SCORE_RANGE CHECK (SCORE_VALUE BETWEEN 0 AND 850),
    SCORE_BAND      VARCHAR2(20) NOT NULL
                    CONSTRAINT CK_SCORE_BAND
                    CHECK (SCORE_BAND IN ('EXCELLENT','GOOD','FAIR','THIN')),
    REPAYMENT_SCORE NUMBER(5,2),
    SAVINGS_SCORE   NUMBER(5,2),
    COMPUTED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_CURRENT      CHAR(1)  DEFAULT 'Y'
                    CONSTRAINT CK_SCORE_CURRENT CHECK (IS_CURRENT IN ('Y','N'))
);

CREATE INDEX IDX_SCORE_MEMBER ON CREDIT_SCORE(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- 5. CREDIT_PASSPORT
-- ----------------------------------------------------------------------------
CREATE TABLE CREDIT_PASSPORT (
    PASSPORT_ID     NUMBER      NOT NULL
                    CONSTRAINT PK_PASSPORT PRIMARY KEY,
    MEMBER_ID       NUMBER      NOT NULL
                    CONSTRAINT FK_PASSPORT_MEMBER REFERENCES MEMBER(MEMBER_ID),
    SCORE_ID        NUMBER      NOT NULL
                    CONSTRAINT FK_PASSPORT_SCORE REFERENCES CREDIT_SCORE(SCORE_ID),
    QR_TOKEN        VARCHAR2(64) NOT NULL
                    CONSTRAINT UQ_PASSPORT_TOKEN UNIQUE,
    PASSPORT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
                    CONSTRAINT CK_PASSPORT_STATUS
                    CHECK (PASSPORT_STATUS IN ('ACTIVE','EXPIRED','REVOKED')),
    GENERATED_AT    TIMESTAMP   DEFAULT SYSTIMESTAMP,
    EXPIRES_AT      TIMESTAMP   NOT NULL,
    VIEW_COUNT      NUMBER      DEFAULT 0
);

CREATE INDEX IDX_PASSPORT_MEMBER ON CREDIT_PASSPORT(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- Read-only view for verification reports
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_PASSPORT_DETAIL AS
SELECT p.PASSPORT_ID,
       p.QR_TOKEN,
       p.PASSPORT_STATUS,
       p.GENERATED_AT,
       p.EXPIRES_AT,
       p.VIEW_COUNT,
       m.MEMBER_ID,
       m.FULL_NAME,
       m.NIN,
       m.DISTRICT,
       s.SCORE_VALUE,
       s.SCORE_BAND
  FROM CREDIT_PASSPORT p
  JOIN MEMBER        m ON m.MEMBER_ID = p.MEMBER_ID
  JOIN CREDIT_SCORE  s ON s.SCORE_ID  = p.SCORE_ID;

-- ----------------------------------------------------------------------------
-- Synonyms (aliases so applications can refer to a stable public name and the
-- underlying object can be repointed without changing application code).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE SYNONYM CLIENTS       FOR MEMBER;
CREATE OR REPLACE SYNONYM LOANS         FOR LOAN_RECORD;
CREATE OR REPLACE SYNONYM SAVINGS       FOR SAVINGS_RECORD;
CREATE OR REPLACE SYNONYM MEMBER_DETAIL FOR V_PASSPORT_DETAIL;

PROMPT SACCOLink schema created successfully.
PROMPT Remember: BEFORE INSERT PK triggers live in sql/04_triggers.sql.

-- ====================================================================
-- >>> 02_plsql.sql
-- ====================================================================
-- ============================================================================
-- SACCOLink
-- PL/SQL: Scoring engine, passport generation, passport verification
-- ============================================================================

-- ----------------------------------------------------------------------------
-- FN_GET_SCORE_BAND : map numeric score (0-850) to a band label
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION FN_GET_SCORE_BAND (p_score IN NUMBER)
RETURN VARCHAR2
IS
BEGIN
    IF p_score >= 700 THEN RETURN 'EXCELLENT';
    ELSIF p_score >= 550 THEN RETURN 'GOOD';
    ELSIF p_score >= 400 THEN RETURN 'FAIR';
    ELSE RETURN 'THIN';
    END IF;
END FN_GET_SCORE_BAND;
/

-- ----------------------------------------------------------------------------
-- SP_COMPUTE_SCORE : compute and store a new score for a member.
--   - Loan Repayment (60%) : repaid/total loans (0-100), -25 per default
--   - Savings Consistency (40%) : months contributed / months since first (0-100)
--   - Composite = (REPAYMENT*0.6 + SAVINGS*0.4) * 8.5  -> 0-850
--   - Marks the previous current score IS_CURRENT = 'N'
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_COMPUTE_SCORE (p_member_id IN NUMBER)
IS
    v_total_loans   NUMBER := 0;
    v_repaid_loans  NUMBER := 0;
    v_default_loans NUMBER := 0;
    v_repay_score   NUMBER := 0;
    v_savings_score NUMBER := 0;
    v_months_data   NUMBER := 0;
    v_months_since  NUMBER := 0;
    v_first_month   DATE;
    v_composite     NUMBER;
    v_band          VARCHAR2(20);
    v_no_member     EXCEPTION;
    PRAGMA EXCEPTION_INIT(v_no_member, -20001);
BEGIN
    -- member must exist
    SELECT COUNT(*) INTO v_total_loans
      FROM MEMBER WHERE MEMBER_ID = p_member_id;
    IF v_total_loans = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'MEMBER_NOT_FOUND');
    END IF;

    -- --- Loan repayment factor (0-100) ---
    SELECT COUNT(*), NVL(SUM(CASE WHEN LOAN_STATUS = 'REPAID'    THEN 1 ELSE 0 END), 0),
           NVL(SUM(CASE WHEN LOAN_STATUS = 'DEFAULTED' THEN 1 ELSE 0 END), 0)
      INTO v_total_loans, v_repaid_loans, v_default_loans
      FROM LOAN_RECORD
     WHERE MEMBER_ID = p_member_id;

    IF v_total_loans > 0 THEN
        v_repay_score := (v_repaid_loans / v_total_loans) * 100
                         - (v_default_loans * 25);
        v_repay_score := GREATEST(v_repay_score, 0);
    ELSE
        v_repay_score := 50; -- neutral when no loan history
    END IF;

    -- --- Savings consistency factor (0-100) ---
    SELECT COUNT(*), MIN(CONTRIBUTION_MONTH)
      INTO v_months_data, v_first_month
      FROM SAVINGS_RECORD
     WHERE MEMBER_ID = p_member_id;

    IF v_months_data > 0 THEN
        v_months_since := MONTHS_BETWEEN(TRUNC(SYSDATE, 'MM'), v_first_month) + 1;
        v_months_since := GREATEST(v_months_since, 1);
        v_savings_score := (v_months_data / v_months_since) * 100;
        v_savings_score := LEAST(v_savings_score, 100);
    ELSE
        v_savings_score := 0;
    END IF;

    -- --- Composite score (0-850) ---
    v_composite := ROUND((v_repay_score * 0.6 + v_savings_score * 0.4) * 8.5, 2);
    v_composite := LEAST(v_composite, 850);
    v_band := FN_GET_SCORE_BAND(v_composite);

    -- previous score no longer current
    UPDATE CREDIT_SCORE SET IS_CURRENT = 'N'
     WHERE MEMBER_ID = p_member_id AND IS_CURRENT = 'Y';

    INSERT INTO CREDIT_SCORE (MEMBER_ID, SCORE_VALUE, SCORE_BAND,
                              REPAYMENT_SCORE, SAVINGS_SCORE)
    VALUES (p_member_id, v_composite, v_band, v_repay_score, v_savings_score);

    DBMS_OUTPUT.PUT_LINE('Score ' || v_composite || ' (' || v_band ||
                         ') computed for member ' || p_member_id);
END SP_COMPUTE_SCORE;
/

-- ----------------------------------------------------------------------------
-- SP_GENERATE_PASSPORT : create a 72-hour credit passport for a member.
--   Requires consent and a current score. QR token is a random 32-char string.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_GENERATE_PASSPORT (
    p_member_id    IN  NUMBER,
    p_passport_id  OUT NUMBER,
    p_qr_token     OUT VARCHAR2
)
IS
    v_score_id  NUMBER;
    v_token     VARCHAR2(64);
    v_consent   CHAR(1);
BEGIN
    -- consent gate
    BEGIN
        SELECT CONSENT_GIVEN INTO v_consent
          FROM MEMBER WHERE MEMBER_ID = p_member_id;
        IF v_consent != 'Y' THEN
            RAISE_APPLICATION_ERROR(-20002, 'CONSENT_NOT_GIVEN');
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'MEMBER_NOT_FOUND');
    END;

    -- current score required
    SELECT SCORE_ID INTO v_score_id
      FROM CREDIT_SCORE
     WHERE MEMBER_ID = p_member_id AND IS_CURRENT = 'Y';

    v_token := DBMS_RANDOM.STRING('X', 32);

    INSERT INTO CREDIT_PASSPORT (MEMBER_ID, SCORE_ID, QR_TOKEN, EXPIRES_AT)
    VALUES (p_member_id, v_score_id, v_token, SYSTIMESTAMP + INTERVAL '3' DAY)
    RETURNING PASSPORT_ID INTO p_passport_id;

    p_qr_token := v_token;
END SP_GENERATE_PASSPORT;
/

-- ----------------------------------------------------------------------------
-- FN_VERIFY_PASSPORT : verify a QR token.
--   Returns 'VALID' / 'EXPIRED' / 'REVOKED' / 'NOT_FOUND'.
--   On VALID, increments the passport VIEW_COUNT.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION FN_VERIFY_PASSPORT (
    p_qr_token      IN  VARCHAR2,
    p_member_name   OUT VARCHAR2,
    p_score_value   OUT NUMBER,
    p_score_band    OUT VARCHAR2,
    p_generated_at  OUT TIMESTAMP,
    p_expires_at    OUT TIMESTAMP
)
RETURN VARCHAR2
IS
    v_status    VARCHAR2(20);
    v_expires   TIMESTAMP;
BEGIN
    SELECT PASSPORT_STATUS, EXPIRES_AT
      INTO v_status, v_expires
      FROM CREDIT_PASSPORT
     WHERE QR_TOKEN = p_qr_token;

    IF v_status = 'REVOKED' THEN
        RETURN 'REVOKED';
    END IF;

    IF v_status = 'ACTIVE' AND v_expires > SYSTIMESTAMP THEN
        SELECT m.FULL_NAME, s.SCORE_VALUE, s.SCORE_BAND,
               p.GENERATED_AT, p.EXPIRES_AT
          INTO p_member_name, p_score_value, p_score_band,
               p_generated_at, p_expires_at
          FROM CREDIT_PASSPORT p
          JOIN MEMBER m       ON m.MEMBER_ID = p.MEMBER_ID
          JOIN CREDIT_SCORE s ON s.SCORE_ID  = p.SCORE_ID
         WHERE p.QR_TOKEN = p_qr_token;

        UPDATE CREDIT_PASSPORT SET VIEW_COUNT = VIEW_COUNT + 1
         WHERE QR_TOKEN = p_qr_token;
        RETURN 'VALID';
    END IF;

    RETURN 'EXPIRED';
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'NOT_FOUND';
END FN_VERIFY_PASSPORT;
/

-- ----------------------------------------------------------------------------
-- SP_EXPIRE_PASSPORTS : mark passports whose EXPIRES_AT has passed.
--   Run manually or via a scheduled DBMS_SCHEDULER job.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_EXPIRE_PASSPORTS
IS
BEGIN
    UPDATE CREDIT_PASSPORT
       SET PASSPORT_STATUS = 'EXPIRED'
     WHERE PASSPORT_STATUS = 'ACTIVE'
       AND EXPIRES_AT < SYSTIMESTAMP;
    COMMIT;
END SP_EXPIRE_PASSPORTS;
/

PROMPT SACCOLink PL/SQL objects created successfully.

-- ====================================================================
-- >>> 04_triggers.sql
-- ====================================================================
-- ============================================================================
-- SACCOLink
-- Triggers -- sequence-based primary keys + business rules
-- Run AFTER sql/01_schema.sql (needs the SEQ_* sequences).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PK auto-increment: BEFORE INSERT populates the NUMBER primary key from the
-- matching sequence, replacing the GENERATED BY DEFAULT AS IDENTITY columns.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MEMBER_BI
BEFORE INSERT ON MEMBER
FOR EACH ROW
WHEN (NEW.MEMBER_ID IS NULL)
BEGIN
    :NEW.MEMBER_ID := SEQ_MEMBER.NEXTVAL;
END TRG_MEMBER_BI;
/

CREATE OR REPLACE TRIGGER TRG_LOAN_BI
BEFORE INSERT ON LOAN_RECORD
FOR EACH ROW
WHEN (NEW.LOAN_ID IS NULL)
BEGIN
    :NEW.LOAN_ID := SEQ_LOAN.NEXTVAL;
END TRG_LOAN_BI;
/

CREATE OR REPLACE TRIGGER TRG_SAVINGS_BI
BEFORE INSERT ON SAVINGS_RECORD
FOR EACH ROW
WHEN (NEW.SAVINGS_ID IS NULL)
BEGIN
    :NEW.SAVINGS_ID := SEQ_SAVINGS.NEXTVAL;
END TRG_SAVINGS_BI;
/

CREATE OR REPLACE TRIGGER TRG_SCORE_BI
BEFORE INSERT ON CREDIT_SCORE
FOR EACH ROW
WHEN (NEW.SCORE_ID IS NULL)
BEGIN
    :NEW.SCORE_ID := SEQ_SCORE.NEXTVAL;
END TRG_SCORE_BI;
/

-- ----------------------------------------------------------------------------
-- Passport defaults: generate the PK, the QR token and the 72-hour expiry in
-- the trigger so a bare INSERT produces a valid passport (business rule: a
-- passport expires 72 hours after generation).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_PASSPORT_BI
BEFORE INSERT ON CREDIT_PASSPORT
FOR EACH ROW
BEGIN
    IF :NEW.PASSPORT_ID IS NULL THEN
        :NEW.PASSPORT_ID := SEQ_PASSPORT.NEXTVAL;
    END IF;
    IF :NEW.QR_TOKEN IS NULL THEN
        :NEW.QR_TOKEN := DBMS_RANDOM.STRING('X', 32);
    END IF;
    IF :NEW.EXPIRES_AT IS NULL THEN
        :NEW.EXPIRES_AT := SYSTIMESTAMP + INTERVAL '3' DAY;
    END IF;
    IF :NEW.VIEW_COUNT IS NULL THEN
        :NEW.VIEW_COUNT := 0;
    END IF;
END TRG_PASSPORT_BI;
/

-- ----------------------------------------------------------------------------
-- Audit trigger: log every consent change on MEMBER into a lightweight
-- CONSENT_AUDIT table (DPPA-aware). This is a small, self-contained audit log
-- that does not disturb the core 5-entity design.
-- ----------------------------------------------------------------------------
CREATE TABLE CONSENT_AUDIT (
    AUDIT_ID        NUMBER NOT NULL,
    MEMBER_ID       NUMBER NOT NULL,
    OLD_CONSENT     CHAR(1),
    NEW_CONSENT     CHAR(1),
    CHANGED_BY      VARCHAR2(128) DEFAULT USER,
    CHANGED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CONSENT_AUDIT PRIMARY KEY (AUDIT_ID)
);

CREATE SEQUENCE SEQ_CONSENT_AUDIT START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_MEMBER_CONSENT_AUDIT
AFTER UPDATE OF CONSENT_GIVEN ON MEMBER
FOR EACH ROW
WHEN (OLD.CONSENT_GIVEN IS NULL OR NEW.CONSENT_GIVEN IS NULL
      OR OLD.CONSENT_GIVEN != NEW.CONSENT_GIVEN)
BEGIN
    INSERT INTO CONSENT_AUDIT (AUDIT_ID, MEMBER_ID, OLD_CONSENT, NEW_CONSENT)
    VALUES (SEQ_CONSENT_AUDIT.NEXTVAL, :NEW.MEMBER_ID,
            :OLD.CONSENT_GIVEN, :NEW.CONSENT_GIVEN);
END TRG_MEMBER_CONSENT_AUDIT;
/

PROMPT SACCOLink triggers created successfully (6 of 8 triggers; the remaining 2 come with the multi-user section).

-- ====================================================================
-- >>> 05_packages.sql
-- ====================================================================
-- ============================================================================
-- SACCOLink
-- Packages -- single entry points wrapping the PL/SQL business logic
-- Run AFTER sql/02_plsql.sql (standalone objects) and sql/04_triggers.sql.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PKG_SACCOINK : public API over scoring + passport workflow.
-- Thin wrappers keep the standalone routines callable by the Java Swing client
-- over JDBC and provide a single versioned entry point for applications.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_SACCOINK AS

    FUNCTION GET_SCORE_BAND(p_score IN NUMBER)
        RETURN VARCHAR2;

    PROCEDURE COMPUTE_SCORE(p_member_id IN NUMBER);

    PROCEDURE GENERATE_PASSPORT(
        p_member_id   IN  NUMBER,
        p_passport_id OUT NUMBER,
        p_qr_token    OUT VARCHAR2);

    FUNCTION VERIFY_PASSPORT(
        p_qr_token     IN  VARCHAR2,
        p_member_name  OUT VARCHAR2,
        p_score_value  OUT NUMBER,
        p_score_band   OUT VARCHAR2,
        p_generated_at OUT TIMESTAMP,
        p_expires_at   OUT TIMESTAMP)
        RETURN VARCHAR2;

    PROCEDURE EXPIRE_PASSPORTS;

    -- Total still owed on a member's ACTIVE loans, computed with an EXPLICIT
    -- CURSOR (OPEN / FETCH / %ROWTYPE / CLOSE) for the PL/SQL coursework.
    FUNCTION OUTSTANDING_BALANCE(p_member_id IN NUMBER) RETURN NUMBER;

END PKG_SACCOINK;
/

CREATE OR REPLACE PACKAGE BODY PKG_SACCOINK AS

    FUNCTION GET_SCORE_BAND(p_score IN NUMBER) RETURN VARCHAR2 IS
    BEGIN
        RETURN FN_GET_SCORE_BAND(p_score);
    END GET_SCORE_BAND;

    PROCEDURE COMPUTE_SCORE(p_member_id IN NUMBER) IS
    BEGIN
        SP_COMPUTE_SCORE(p_member_id);
    END COMPUTE_SCORE;

    PROCEDURE GENERATE_PASSPORT(
        p_member_id   IN  NUMBER,
        p_passport_id OUT NUMBER,
        p_qr_token    OUT VARCHAR2) IS
    BEGIN
        SP_GENERATE_PASSPORT(p_member_id, p_passport_id, p_qr_token);
    END GENERATE_PASSPORT;

    FUNCTION VERIFY_PASSPORT(
        p_qr_token     IN  VARCHAR2,
        p_member_name  OUT VARCHAR2,
        p_score_value  OUT NUMBER,
        p_score_band   OUT VARCHAR2,
        p_generated_at OUT TIMESTAMP,
        p_expires_at   OUT TIMESTAMP) RETURN VARCHAR2 IS
    BEGIN
        RETURN FN_VERIFY_PASSPORT(p_qr_token, p_member_name, p_score_value,
                                  p_score_band, p_generated_at, p_expires_at);
    END VERIFY_PASSPORT;

    PROCEDURE EXPIRE_PASSPORTS IS
    BEGIN
        SP_EXPIRE_PASSPORTS;
    END EXPIRE_PASSPORTS;

    FUNCTION OUTSTANDING_BALANCE(p_member_id IN NUMBER) RETURN NUMBER IS
        CURSOR c_outstanding IS
            SELECT *
              FROM LOAN_RECORD
             WHERE MEMBER_ID = p_member_id
               AND LOAN_STATUS = 'ACTIVE';
        v_balance NUMBER := 0;
        v_row     LOAN_RECORD%ROWTYPE;
    BEGIN
        OPEN c_outstanding;
        LOOP
            FETCH c_outstanding INTO v_row;
            EXIT WHEN c_outstanding%NOTFOUND;
            v_balance := v_balance + v_row.LOAN_AMOUNT;
        END LOOP;
        CLOSE c_outstanding;
        RETURN v_balance;
    EXCEPTION
        WHEN OTHERS THEN
            IF c_outstanding%ISOPEN THEN
                CLOSE c_outstanding;
            END IF;
            RAISE;
    END OUTSTANDING_BALANCE;

END PKG_SACCOINK;
/

-- ----------------------------------------------------------------------------
-- PKG_SACCOINK_REPORT : aggregate statistics for dashboards and reports.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_SACCOINK_REPORT AS

    FUNCTION COUNT_MEMBERS RETURN NUMBER;
    FUNCTION COUNT_MEMBERS_WITH_CONSENT RETURN NUMBER;
    FUNCTION AVG_CURRENT_SCORE RETURN NUMBER;
    FUNCTION COUNT_PASSPORTS(p_status IN VARCHAR2 DEFAULT NULL) RETURN NUMBER;
    FUNCTION TOTAL_SAVINGS(p_member_id IN NUMBER DEFAULT NULL) RETURN NUMBER;
    FUNCTION TOTAL_LOANS(p_member_id IN NUMBER DEFAULT NULL) RETURN NUMBER;

    PROCEDURE MEMBER_SUMMARY(
        p_member_id IN  NUMBER,
        p_loans     OUT NUMBER,
        p_savings   OUT NUMBER,
        p_score     OUT NUMBER,
        p_band      OUT VARCHAR2);

END PKG_SACCOINK_REPORT;
/

CREATE OR REPLACE PACKAGE BODY PKG_SACCOINK_REPORT AS

    FUNCTION COUNT_MEMBERS RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM MEMBER;
        RETURN v_count;
    END COUNT_MEMBERS;

    FUNCTION COUNT_MEMBERS_WITH_CONSENT RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM MEMBER WHERE CONSENT_GIVEN = 'Y';
        RETURN v_count;
    END COUNT_MEMBERS_WITH_CONSENT;

    FUNCTION AVG_CURRENT_SCORE RETURN NUMBER IS
        v_avg NUMBER;
    BEGIN
        SELECT NVL(AVG(SCORE_VALUE), 0) INTO v_avg
          FROM CREDIT_SCORE WHERE IS_CURRENT = 'Y';
        RETURN v_avg;
    END AVG_CURRENT_SCORE;

    FUNCTION COUNT_PASSPORTS(p_status IN VARCHAR2 DEFAULT NULL) RETURN NUMBER IS
        v_count NUMBER;
    BEGIN
        IF p_status IS NULL THEN
            SELECT COUNT(*) INTO v_count FROM CREDIT_PASSPORT;
        ELSE
            SELECT COUNT(*) INTO v_count FROM CREDIT_PASSPORT
             WHERE PASSPORT_STATUS = p_status;
        END IF;
        RETURN v_count;
    END COUNT_PASSPORTS;

    FUNCTION TOTAL_SAVINGS(p_member_id IN NUMBER DEFAULT NULL) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        IF p_member_id IS NULL THEN
            SELECT NVL(SUM(AMOUNT_CONTRIBUTED), 0) INTO v_total FROM SAVINGS_RECORD;
        ELSE
            SELECT NVL(SUM(AMOUNT_CONTRIBUTED), 0) INTO v_total FROM SAVINGS_RECORD
             WHERE MEMBER_ID = p_member_id;
        END IF;
        RETURN v_total;
    END TOTAL_SAVINGS;

    FUNCTION TOTAL_LOANS(p_member_id IN NUMBER DEFAULT NULL) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        IF p_member_id IS NULL THEN
            SELECT NVL(SUM(LOAN_AMOUNT), 0) INTO v_total FROM LOAN_RECORD;
        ELSE
            SELECT NVL(SUM(LOAN_AMOUNT), 0) INTO v_total FROM LOAN_RECORD
             WHERE MEMBER_ID = p_member_id;
        END IF;
        RETURN v_total;
    END TOTAL_LOANS;

    PROCEDURE MEMBER_SUMMARY(
        p_member_id IN  NUMBER,
        p_loans     OUT NUMBER,
        p_savings   OUT NUMBER,
        p_score     OUT NUMBER,
        p_band      OUT VARCHAR2) IS
        v_member_id NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_member_id FROM MEMBER WHERE MEMBER_ID = p_member_id;
        IF v_member_id = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'MEMBER_NOT_FOUND');
        END IF;

        SELECT COUNT(*) INTO p_loans FROM LOAN_RECORD WHERE MEMBER_ID = p_member_id;
        SELECT NVL(SUM(AMOUNT_CONTRIBUTED), 0) INTO p_savings
          FROM SAVINGS_RECORD WHERE MEMBER_ID = p_member_id;

        BEGIN
            SELECT SCORE_VALUE, SCORE_BAND INTO p_score, p_band
              FROM CREDIT_SCORE
             WHERE MEMBER_ID = p_member_id AND IS_CURRENT = 'Y';
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                p_score := NULL;
                p_band  := 'NO_SCORE';
        END;
    END MEMBER_SUMMARY;

END PKG_SACCOINK_REPORT;
/

PROMPT SACCOLink packages created successfully (2 packages).

-- ====================================================================
-- >>> 03_sample_data.sql
-- ====================================================================
-- ============================================================================
-- SACCOLink
-- Sample data + demonstration run (extended mock dataset)
-- NOTE: NIN values below are exactly 14 characters (NIRA format), e.g.
--   CM012345678901  =  'C','M' + 12 digits  =  14 characters
--
-- Primary keys are left NULL / unset so the BEFORE INSERT triggers in
-- sql/04_triggers.sql populate them from the SEQ_* sequences.
-- ============================================================================
SET SERVEROUTPUT ON

-- --- Members (7 personas) ---
INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM012345678901', 'Grace Namukasa',  '0772000001', 'Kampala',  'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM112345678902', 'Okello Moses',    '0772000002', 'Gulu',     'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM212345678903', 'Hassan Ssekabira','0772000003', 'Wakiso',   'N');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM312345678904', 'Amina Nakato',    '0772000004', 'Masaka',   'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM412345678905', 'Sarah Kintu',     '0772000005', 'Jinja',    'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM512345678906', 'John Ochieng',    '0772000006', 'Lira',     'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM612345678907', 'Betty Nansubuga', '0772000007', 'Mbarara',  'Y');

COMMIT;

-- --- Loans ---
-- Grace (3 repaid)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2021-03-01', DATE '2022-03-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Grace Namukasa';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1500000, DATE '2022-05-01', DATE '2023-05-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Grace Namukasa';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 3000000, DATE '2023-08-01', DATE '2024-08-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Grace Namukasa';
-- Okello (1 active)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1000000, DATE '2025-01-15', NULL, 'ACTIVE' FROM MEMBER WHERE FULL_NAME='Okello Moses';
-- Hassan (1 repaid + 1 defaulted)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1500000, DATE '2022-01-01', DATE '2022-12-31', 'REPAID' FROM MEMBER WHERE FULL_NAME='Hassan Ssekabira';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2023-06-01', NULL, 'DEFAULTED' FROM MEMBER WHERE FULL_NAME='Hassan Ssekabira';
-- Sarah (2 repaid)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1000000, DATE '2022-02-01', DATE '2023-02-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Sarah Kintu';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1500000, DATE '2023-10-01', DATE '2024-10-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Sarah Kintu';
-- John (1 repaid + 1 active)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 800000,  DATE '2023-03-01', DATE '2024-03-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='John Ochieng';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2026-01-10', NULL, 'ACTIVE' FROM MEMBER WHERE FULL_NAME='John Ochieng';
-- Betty (3 repaid)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2020-01-01', DATE '2021-01-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Betty Nansubuga';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 3000000, DATE '2021-06-01', DATE '2022-06-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Betty Nansubuga';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 4000000, DATE '2022-09-01', DATE '2023-09-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Betty Nansubuga';

-- --- Savings (217 monthly entries) ---
BEGIN
    -- Grace: 60 months @ 400,000
    FOR i IN 0 .. 59 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2021-01-01', i), 400000
          FROM MEMBER WHERE FULL_NAME = 'Grace Namukasa';
    END LOOP;
    -- Okello: 24 months @ 50,000
    FOR i IN 0 .. 23 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2023-08-01', i), 50000
          FROM MEMBER WHERE FULL_NAME = 'Okello Moses';
    END LOOP;
    -- Hassan: 30 months @ 200,000
    FOR i IN 0 .. 29 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2022-07-01', i), 200000
          FROM MEMBER WHERE FULL_NAME = 'Hassan Ssekabira';
    END LOOP;
    -- Amina: 1 month @ 100,000
    INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
    SELECT MEMBER_ID, TRUNC(SYSDATE, 'MM'), 100000
      FROM MEMBER WHERE FULL_NAME = 'Amina Nakato';
    -- Sarah: 36 months @ 150,000
    FOR i IN 0 .. 35 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2023-01-01', i), 150000
          FROM MEMBER WHERE FULL_NAME = 'Sarah Kintu';
    END LOOP;
    -- John: 18 months @ 100,000
    FOR i IN 0 .. 17 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2025-01-01', i), 100000
          FROM MEMBER WHERE FULL_NAME = 'John Ochieng';
    END LOOP;
    -- Betty: 48 months @ 250,000
    FOR i IN 0 .. 47 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2022-01-01', i), 250000
          FROM MEMBER WHERE FULL_NAME = 'Betty Nansubuga';
    END LOOP;
END;
/

COMMIT;

-- --- Compute scores for everyone ---
BEGIN
    FOR r IN (SELECT MEMBER_ID, FULL_NAME FROM MEMBER) LOOP
        DBMS_OUTPUT.PUT_LINE('Computing score for ' || r.FULL_NAME);
        SP_COMPUTE_SCORE(r.MEMBER_ID);
    END LOOP;
END;
/

-- --- Demo: generate + verify a passport for Grace, generate one for Sarah ---
DECLARE
    v_member_id NUMBER;
    v_pid       NUMBER;
    v_token     VARCHAR2(64);
    v_result    VARCHAR2(20);
    v_name      VARCHAR2(200);
    v_score     NUMBER;
    v_band      VARCHAR2(20);
    v_gen       TIMESTAMP;
    v_exp       TIMESTAMP;
BEGIN
    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'Grace Namukasa';
    SP_GENERATE_PASSPORT(p_member_id   => v_member_id,
                         p_passport_id => v_pid,
                         p_qr_token    => v_token);
    DBMS_OUTPUT.PUT_LINE('Passport ' || v_pid || ' generated, token = ' || v_token);

    v_result := FN_VERIFY_PASSPORT(v_token, v_name, v_score, v_band, v_gen, v_exp);
    DBMS_OUTPUT.PUT_LINE('Verify result: ' || v_result || ' | ' || v_name ||
                         ' | Score: ' || v_score || ' (' || v_band || ')');

    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'Sarah Kintu';
    SP_GENERATE_PASSPORT(p_member_id   => v_member_id,
                         p_passport_id => v_pid,
                         p_qr_token    => v_token);
    DBMS_OUTPUT.PUT_LINE('Passport ' || v_pid || ' generated for Sarah Kintu, token = ' || v_token);

    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'Betty Nansubuga';
    SP_GENERATE_PASSPORT(p_member_id   => v_member_id,
                         p_passport_id => v_pid,
                         p_qr_token    => v_token);
    DBMS_OUTPUT.PUT_LINE('Passport ' || v_pid || ' generated for Betty Nansubuga, token = ' || v_token);

    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'John Ochieng';
    SP_GENERATE_PASSPORT(p_member_id   => v_member_id,
                         p_passport_id => v_pid,
                         p_qr_token    => v_token);
    DBMS_OUTPUT.PUT_LINE('Passport ' || v_pid || ' generated for John Ochieng, token = ' || v_token);
END;
/

-- --- Package demo: member summary via PKG_SACCOINK_REPORT ---
DECLARE
    v_member_id NUMBER;
    v_loans   NUMBER;
    v_savings NUMBER;
    v_score   NUMBER;
    v_band    VARCHAR2(20);
BEGIN
    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'Grace Namukasa';
    PKG_SACCOINK_REPORT.MEMBER_SUMMARY(v_member_id, v_loans, v_savings, v_score, v_band);
    DBMS_OUTPUT.PUT_LINE('Member ' || v_member_id || ' summary -> loans: ' || v_loans ||
                         ', total savings: ' || v_savings ||
                         ', score: ' || v_score || ' (' || v_band || ')');
END;
/

-- --- Final report queries ---
SELECT m.FULL_NAME, s.SCORE_VALUE, s.SCORE_BAND
  FROM CREDIT_SCORE s JOIN MEMBER m ON m.MEMBER_ID = s.MEMBER_ID
 WHERE s.IS_CURRENT = 'Y'
 ORDER BY s.SCORE_VALUE DESC;

SELECT m.FULL_NAME, COUNT(s.SAVINGS_ID) AS MONTHS_SAVED,
       NVL(SUM(s.AMOUNT_CONTRIBUTED), 0) AS TOTAL_SAVED
  FROM MEMBER m
  LEFT JOIN SAVINGS_RECORD s ON s.MEMBER_ID = m.MEMBER_ID
 GROUP BY m.FULL_NAME, m.MEMBER_ID
 ORDER BY MONTHS_SAVED DESC;

SELECT * FROM V_PASSPORT_DETAIL;

SELECT AUDIT_ID, MEMBER_ID, OLD_CONSENT, NEW_CONSENT, CHANGED_BY, CHANGED_AT
  FROM CONSENT_AUDIT;

-- ====================================================================
-- >>> 06_multiuser.sql
-- ====================================================================
-- ============================================================================
-- SACCOLink
-- Multi-user simulation: APP_USER (MEMBER / SACCO) + LOAN_REQUEST workflow
--
--   * Two account types
--       - MEMBER : sees ONLY their own history (loans, savings, scores,
--                  passports) and can generate a token for a creditor.
--       - SACCO  : full access; verifies creditworthiness when a member
--                  requests a loan, then approves / rejects the request
--                  (approval records the loan on LOAN_RECORD).
--   * V_MY_LOANS / V_MY_SAVINGS / V_MY_SCORES / V_MY_PASSPORTS / V_MY_PROFILE
--     views scope each user to their own rows using an application context
--     (saccolink_ctx) set at login. SACCO (MEMBER_ID = NULL) sees all rows.
--
-- Run AFTER 01_schema.sql, 02_plsql.sql, 04_triggers.sql, 05_packages.sql
-- and 03_sample_data.sql (needs MEMBER rows for the user seeds).
-- ============================================================================
SET SERVEROUTPUT ON

-- ----------------------------------------------------------------------------
-- Cleanup (tolerant, so 06 also runs standalone / after a fresh 01-schema reset)
-- ----------------------------------------------------------------------------
DECLARE
BEGIN
    -- The context must be dropped BEFORE its USING package, otherwise a later
    -- CREATE OR REPLACE CONTEXT leaves SET_CONTEXT raising ORA-01031.
    EXECUTE IMMEDIATE 'DROP CONTEXT saccolink_ctx';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

DECLARE
BEGIN
    FOR o IN (SELECT object_name, object_type FROM user_objects
               WHERE object_name IN ('APP_USER', 'LOAN_REQUEST',
                                     'SEQ_APP_USER', 'SEQ_LOAN_REQUEST',
                                     'V_MY_PASSPORTS', 'V_MY_SCORES',
                                     'V_MY_SAVINGS', 'V_MY_LOANS', 'V_MY_PROFILE',
                                     'PKG_APP_SESSION')
                 AND object_type IN ('TABLE', 'SEQUENCE', 'VIEW', 'PACKAGE',
                                     'PACKAGE BODY', 'PROCEDURE', 'FUNCTION')) LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP ' || o.object_type || ' "' || o.object_name || '"';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- Sequences (PKs stay classic NUMBER + BEFORE INSERT trigger pattern)
-- ----------------------------------------------------------------------------
CREATE SEQUENCE SEQ_APP_USER      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOAN_REQUEST  START WITH 1 INCREMENT BY 1 NOCACHE;

-- ----------------------------------------------------------------------------
-- APP_USER : application login (not a database account)
-- ----------------------------------------------------------------------------
CREATE TABLE APP_USER (
    USER_ID       NUMBER       NOT NULL CONSTRAINT PK_APP_USER PRIMARY KEY,
    USERNAME      VARCHAR2(50) NOT NULL CONSTRAINT UQ_APP_USER_USERNAME UNIQUE,
    PASSWORD_HASH VARCHAR2(64) NOT NULL,   -- SHA-256 hex (username#password)
    ROLE          VARCHAR2(10) NOT NULL
                  CONSTRAINT CK_APP_USER_ROLE CHECK (ROLE IN ('MEMBER','SACCO')),
    MEMBER_ID     NUMBER
                  CONSTRAINT FK_APP_USER_MEMBER REFERENCES MEMBER(MEMBER_ID),
    DISPLAY_NAME  VARCHAR2(200) NOT NULL,
    IS_ACTIVE     CHAR(1)       DEFAULT 'Y'
                  CONSTRAINT CK_APP_USER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_APP_USER_BI
BEFORE INSERT ON APP_USER FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        SELECT SEQ_APP_USER.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;
END;
/

-- ----------------------------------------------------------------------------
-- LOAN_REQUEST : member asks for a loan; SACCO reviews it
-- ----------------------------------------------------------------------------
CREATE TABLE LOAN_REQUEST (
    REQUEST_ID       NUMBER       NOT NULL CONSTRAINT PK_LOAN_REQUEST PRIMARY KEY,
    MEMBER_ID        NUMBER       NOT NULL
                     CONSTRAINT FK_LR_MEMBER REFERENCES MEMBER(MEMBER_ID),
    REQUESTED_AMOUNT NUMBER(15,2) NOT NULL
                     CONSTRAINT CK_LR_AMOUNT CHECK (REQUESTED_AMOUNT > 0),
    PURPOSE          VARCHAR2(500),
    REQUESTED_AT     TIMESTAMP    DEFAULT SYSTIMESTAMP,
    STATUS           VARCHAR2(20) DEFAULT 'PENDING' NOT NULL
                     CONSTRAINT CK_LR_STATUS
                     CHECK (STATUS IN ('PENDING','APPROVED','REJECTED')),
    REVIEWED_BY      VARCHAR2(50),
    REVIEWED_AT      TIMESTAMP
);

CREATE INDEX IDX_LR_MEMBER ON LOAN_REQUEST(MEMBER_ID);
CREATE INDEX IDX_LR_STATUS ON LOAN_REQUEST(STATUS);

CREATE OR REPLACE TRIGGER TRG_LOAN_REQUEST_BI
BEFORE INSERT ON LOAN_REQUEST FOR EACH ROW
BEGIN
    IF :NEW.REQUEST_ID IS NULL THEN
        SELECT SEQ_LOAN_REQUEST.NEXTVAL INTO :NEW.REQUEST_ID FROM DUAL;
    END IF;
END;
/

-- ----------------------------------------------------------------------------
-- Application context + session package (drives the V_MY_* views)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_APP_SESSION AS
    PROCEDURE SET_MEMBER(p_member_id IN NUMBER);
    PROCEDURE CLEAR;
END PKG_APP_SESSION;
/

CREATE OR REPLACE CONTEXT saccolink_ctx USING PKG_APP_SESSION;

CREATE OR REPLACE PACKAGE BODY PKG_APP_SESSION AS
    PROCEDURE SET_MEMBER(p_member_id IN NUMBER) IS
    BEGIN
        DBMS_SESSION.SET_CONTEXT('saccolink_ctx', 'MEMBER_ID',
                                 TO_CHAR(p_member_id));
    END SET_MEMBER;

    PROCEDURE CLEAR IS
    BEGIN
        DBMS_SESSION.CLEAR_CONTEXT('saccolink_ctx');
    END CLEAR;
END PKG_APP_SESSION;
/

-- ----------------------------------------------------------------------------
-- Password hashing + login
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION FN_HASH_PASSWORD (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2
) RETURN VARCHAR2 IS
    v_hash VARCHAR2(64);
BEGIN
    -- STANDARD_HASH is a SQL function only, so it is called dynamically.
    EXECUTE IMMEDIATE
        'SELECT LOWER(RAWTOHEX(STANDARD_HASH(:1, ''SHA256''))) FROM DUAL'
        INTO v_hash USING p_username || '#' || p_password;
    RETURN v_hash;
END FN_HASH_PASSWORD;
/

-- SP_LOGIN : validates an APP_USER credential and returns the session fields.
-- On success it also sets the application context for the V_MY_* views.
CREATE OR REPLACE PROCEDURE SP_LOGIN (
    p_username     IN  VARCHAR2,
    p_password     IN  VARCHAR2,
    p_user_id      OUT NUMBER,
    p_role         OUT VARCHAR2,
    p_member_id    OUT NUMBER,
    p_display_name OUT VARCHAR2,
    p_ok           OUT NUMBER
) IS
    v_member_id NUMBER;
BEGIN
    p_ok := 0;
    SELECT USER_ID, ROLE, MEMBER_ID, DISPLAY_NAME
      INTO p_user_id, p_role, v_member_id, p_display_name
      FROM APP_USER
     WHERE USERNAME = p_username
       AND PASSWORD_HASH = FN_HASH_PASSWORD(p_username, p_password)
       AND IS_ACTIVE = 'Y';

    p_member_id := v_member_id;
    p_ok := 1;
    PKG_APP_SESSION.SET_MEMBER(v_member_id);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_ok := 0;
        p_user_id      := NULL;
        p_role         := NULL;
        p_member_id    := NULL;
        p_display_name := NULL;
END SP_LOGIN;
/

-- ----------------------------------------------------------------------------
-- Loan request workflow
-- ----------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_REQUEST_LOAN (
    p_member_id IN NUMBER,
    p_amount    IN NUMBER,
    p_purpose   IN VARCHAR2
) IS
BEGIN
    INSERT INTO LOAN_REQUEST (MEMBER_ID, REQUESTED_AMOUNT, PURPOSE)
    VALUES (p_member_id, p_amount, p_purpose);
    COMMIT;
END SP_REQUEST_LOAN;
/

-- SP_REVIEW_LOAN : SACCO decides on a pending request. 'APPROVED' also records
-- the loan on LOAN_RECORD as ACTIVE (disbursed today). 'REJECTED' just updates.
CREATE OR REPLACE PROCEDURE SP_REVIEW_LOAN (
    p_request_id  IN NUMBER,
    p_decision    IN VARCHAR2,
    p_reviewed_by IN VARCHAR2
) IS
    v_member_id NUMBER;
    v_amount    NUMBER;
BEGIN
    SELECT MEMBER_ID, REQUESTED_AMOUNT
      INTO v_member_id, v_amount
      FROM LOAN_REQUEST WHERE REQUEST_ID = p_request_id;

    IF UPPER(p_decision) = 'APPROVED' THEN
        INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE,
                                 REPAYMENT_DATE, LOAN_STATUS)
        VALUES (v_member_id, v_amount, TRUNC(SYSDATE), NULL, 'ACTIVE');

        UPDATE LOAN_REQUEST
           SET STATUS = 'APPROVED', REVIEWED_BY = p_reviewed_by,
               REVIEWED_AT = SYSTIMESTAMP
         WHERE REQUEST_ID = p_request_id;
    ELSIF UPPER(p_decision) = 'REJECTED' THEN
        UPDATE LOAN_REQUEST
           SET STATUS = 'REJECTED', REVIEWED_BY = p_reviewed_by,
               REVIEWED_AT = SYSTIMESTAMP
         WHERE REQUEST_ID = p_request_id;
    ELSE
        RAISE_APPLICATION_ERROR(-20010, 'INVALID_DECISION');
    END IF;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20011, 'REQUEST_NOT_FOUND');
END SP_REVIEW_LOAN;
/

-- ----------------------------------------------------------------------------
-- Per-user views.
-- A MEMBER only ever sees their own rows; SACCO (context MEMBER_ID = NULL)
-- sees everything. Used by the GUI DAOs and demonstrable in SQL Developer.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_MY_LOANS AS
SELECT l.LOAN_ID, l.MEMBER_ID, m.FULL_NAME AS MEMBER_NAME,
       l.LOAN_AMOUNT, l.DISBURSEMENT_DATE, l.REPAYMENT_DATE, l.LOAN_STATUS
  FROM LOAN_RECORD l
  JOIN MEMBER m ON m.MEMBER_ID = l.MEMBER_ID
 WHERE SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID') IS NULL
    OR l.MEMBER_ID = TO_NUMBER(SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID'));

CREATE OR REPLACE VIEW V_MY_SAVINGS AS
SELECT s.SAVINGS_ID, s.MEMBER_ID, m.FULL_NAME AS MEMBER_NAME,
       s.CONTRIBUTION_MONTH, s.AMOUNT_CONTRIBUTED
  FROM SAVINGS_RECORD s
  JOIN MEMBER m ON m.MEMBER_ID = s.MEMBER_ID
 WHERE SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID') IS NULL
    OR s.MEMBER_ID = TO_NUMBER(SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID'));

CREATE OR REPLACE VIEW V_MY_SCORES AS
SELECT s.SCORE_ID, s.MEMBER_ID, m.FULL_NAME AS MEMBER_NAME, s.SCORE_VALUE,
       s.SCORE_BAND, s.REPAYMENT_SCORE, s.SAVINGS_SCORE,
       s.COMPUTED_AT, s.IS_CURRENT
  FROM CREDIT_SCORE s
  JOIN MEMBER m ON m.MEMBER_ID = s.MEMBER_ID
 WHERE SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID') IS NULL
    OR s.MEMBER_ID = TO_NUMBER(SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID'));

CREATE OR REPLACE VIEW V_MY_PASSPORTS AS
SELECT p.PASSPORT_ID, p.QR_TOKEN, p.PASSPORT_STATUS, p.GENERATED_AT,
       p.EXPIRES_AT, p.VIEW_COUNT, m.MEMBER_ID, m.FULL_NAME, m.NIN,
       m.DISTRICT, s.SCORE_VALUE, s.SCORE_BAND
  FROM CREDIT_PASSPORT p
  JOIN MEMBER m ON m.MEMBER_ID = p.MEMBER_ID
  JOIN CREDIT_SCORE s ON s.SCORE_ID = p.SCORE_ID
 WHERE SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID') IS NULL
    OR p.MEMBER_ID = TO_NUMBER(SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID'));

CREATE OR REPLACE VIEW V_MY_PROFILE AS
SELECT MEMBER_ID, NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN,
       CREATED_AT
  FROM MEMBER
 WHERE SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID') IS NULL
    OR MEMBER_ID = TO_NUMBER(SYS_CONTEXT('saccolink_ctx', 'MEMBER_ID'));

-- ----------------------------------------------------------------------------
-- Seed application users
-- ----------------------------------------------------------------------------
INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'sacco',  FN_HASH_PASSWORD('sacco',  'sacco123'),
       'SACCO', NULL, 'SACCO Officer' FROM DUAL;

INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'grace', FN_HASH_PASSWORD('grace', 'member123'), 'MEMBER', MEMBER_ID, FULL_NAME
  FROM MEMBER WHERE FULL_NAME = 'Grace Namukasa';

INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'okello', FN_HASH_PASSWORD('okello', 'member123'), 'MEMBER', MEMBER_ID, FULL_NAME
  FROM MEMBER WHERE FULL_NAME = 'Okello Moses';

INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'hassan', FN_HASH_PASSWORD('hassan', 'member123'), 'MEMBER', MEMBER_ID, FULL_NAME
  FROM MEMBER WHERE FULL_NAME = 'Hassan Ssekabira';

INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'amina', FN_HASH_PASSWORD('amina', 'member123'), 'MEMBER', MEMBER_ID, FULL_NAME
  FROM MEMBER WHERE FULL_NAME = 'Amina Nakato';

INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'sarah', FN_HASH_PASSWORD('sarah', 'member123'), 'MEMBER', MEMBER_ID, FULL_NAME
  FROM MEMBER WHERE FULL_NAME = 'Sarah Kintu';

INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'john', FN_HASH_PASSWORD('john', 'member123'), 'MEMBER', MEMBER_ID, FULL_NAME
  FROM MEMBER WHERE FULL_NAME = 'John Ochieng';

INSERT INTO APP_USER (USERNAME, PASSWORD_HASH, ROLE, MEMBER_ID, DISPLAY_NAME)
SELECT 'betty', FN_HASH_PASSWORD('betty', 'member123'), 'MEMBER', MEMBER_ID, FULL_NAME
  FROM MEMBER WHERE FULL_NAME = 'Betty Nansubuga';

-- ----------------------------------------------------------------------------
-- Seed a couple of loan requests
-- ----------------------------------------------------------------------------
INSERT INTO LOAN_REQUEST (MEMBER_ID, REQUESTED_AMOUNT, PURPOSE)
SELECT MEMBER_ID, 2500000, 'School fees'
  FROM MEMBER WHERE FULL_NAME = 'John Ochieng';

INSERT INTO LOAN_REQUEST (MEMBER_ID, REQUESTED_AMOUNT, PURPOSE)
SELECT MEMBER_ID, 1200000, 'Shop stock'
  FROM MEMBER WHERE FULL_NAME = 'Amina Nakato';

COMMIT;

-- ----------------------------------------------------------------------------
-- Demonstration run
-- ----------------------------------------------------------------------------
DECLARE
    v_ok     NUMBER;
    v_uid    NUMBER;
    v_role   VARCHAR2(20);
    v_mid    NUMBER;
    v_name   VARCHAR2(200);
    v_req_id NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- SP_LOGIN (sacco / sacco123) ---');
    SP_LOGIN('sacco', 'sacco123', v_uid, v_role, v_mid, v_name, v_ok);
    DBMS_OUTPUT.PUT_LINE('ok=' || v_ok || ' user_id=' || v_uid ||
                         ' role=' || v_role || ' member_id=' || NVL(TO_CHAR(v_mid),'NULL') ||
                         ' name=' || v_name);

    DBMS_OUTPUT.PUT_LINE('--- SP_LOGIN (wrong password) ---');
    SP_LOGIN('sacco', 'wrong', v_uid, v_role, v_mid, v_name, v_ok);
    DBMS_OUTPUT.PUT_LINE('ok=' || v_ok);

    DBMS_OUTPUT.PUT_LINE('--- SP_LOGIN (grace / member123) ---');
    SP_LOGIN('grace', 'member123', v_uid, v_role, v_mid, v_name, v_ok);
    DBMS_OUTPUT.PUT_LINE('ok=' || v_ok || ' role=' || v_role ||
                         ' member_id=' || v_mid || ' name=' || v_name);

    DBMS_OUTPUT.PUT_LINE('--- Grace requests a 1,000,000 loan ---');
    SP_REQUEST_LOAN(v_mid, 1000000, 'Emergency medical bills');

    DBMS_OUTPUT.PUT_LINE('--- V_MY_LOANS for Grace (own rows only) ---');
    FOR r IN (SELECT LOAN_ID, MEMBER_NAME, LOAN_AMOUNT, LOAN_STATUS
                FROM V_MY_LOANS ORDER BY LOAN_ID) LOOP
        DBMS_OUTPUT.PUT_LINE('loan ' || r.LOAN_ID || ' | ' || r.MEMBER_NAME ||
                             ' | ' || r.LOAN_AMOUNT || ' | ' || r.LOAN_STATUS);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('--- SACCO reviews the first PENDING request ---');
    SELECT REQUEST_ID INTO v_req_id FROM LOAN_REQUEST
     WHERE STATUS = 'PENDING' AND ROWNUM = 1 ORDER BY REQUESTED_AT;
    SP_REVIEW_LOAN(v_req_id, 'APPROVED', 'sacco');
    DBMS_OUTPUT.PUT_LINE('Request ' || v_req_id || ' APPROVED - loan recorded.');

    SELECT REQUEST_ID INTO v_req_id FROM LOAN_REQUEST
     WHERE STATUS = 'PENDING' AND ROWNUM = 1 ORDER BY REQUESTED_AT;
    SP_REVIEW_LOAN(v_req_id, 'REJECTED', 'sacco');
    DBMS_OUTPUT.PUT_LINE('Request ' || v_req_id || ' REJECTED.');

    DBMS_OUTPUT.PUT_LINE('--- SACCO (context cleared) sees ALL loans ---');
    PKG_APP_SESSION.SET_MEMBER(NULL);
    FOR r IN (SELECT COUNT(*) AS N FROM V_MY_LOANS) LOOP
        DBMS_OUTPUT.PUT_LINE('SACCO sees ' || r.N || ' loan row(s).');
    END LOOP;
END;
/

SELECT U.USERNAME, U.ROLE, M.FULL_NAME, U.IS_ACTIVE
  FROM APP_USER U LEFT JOIN MEMBER M ON M.MEMBER_ID = U.MEMBER_ID
 ORDER BY U.USER_ID;

SELECT REQUEST_ID, MEMBER_ID, REQUESTED_AMOUNT, PURPOSE, STATUS, REVIEWED_BY
  FROM LOAN_REQUEST ORDER BY REQUEST_ID;

PROMPT SACCOLink multi-user simulation installed.

-- ============================================================================
-- INSTALL COMPLETE - verify
-- ============================================================================
SET SERVEROUTPUT ON
DECLARE
    v_members   NUMBER;
    v_loans     NUMBER;
    v_savings   NUMBER;
    v_passports NUMBER;
    v_users     NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_members   FROM MEMBER;
    SELECT COUNT(*) INTO v_loans     FROM LOAN_RECORD;
    SELECT COUNT(*) INTO v_savings   FROM SAVINGS_RECORD;
    SELECT COUNT(*) INTO v_passports FROM CREDIT_PASSPORT;
    SELECT COUNT(*) INTO v_users     FROM APP_USER;
    DBMS_OUTPUT.PUT_LINE('Members       : ' || v_members);
    DBMS_OUTPUT.PUT_LINE('Loans         : ' || v_loans);
    DBMS_OUTPUT.PUT_LINE('Savings rows  : ' || v_savings);
    DBMS_OUTPUT.PUT_LINE('Passports     : ' || v_passports);
    DBMS_OUTPUT.PUT_LINE('App users     : ' || v_users);
END;
/

-- ====================================================================
-- >>> 07_queries.sql
-- ====================================================================
-- ============================================================================
-- SACCOLink
-- Part IV  : SQL Programming -- demonstration queries
-- Part V   : Cursors -- explicit cursor demo (anonymous block)
--
-- Every category required by the practical paper is demonstrated below with a
-- comment explaining what the query does. Runs at the end of this install,
-- after the schema, PL/SQL, triggers, packages, sample data and multi-user
-- layer above have been created.
-- ============================================================================

PROMPT ==================== PART IV : SQL PROGRAMMING ====================

-- ----------------------------------------------------------------------------
-- 1. SIMPLE SELECT + WHERE + ORDER BY
-- Members registered in a specific district, newest first.
-- ----------------------------------------------------------------------------
PROMPT -- 1. SELECT with WHERE and ORDER BY
SELECT FULL_NAME, PHONE_NUMBER, DISTRICT
  FROM MEMBER
 WHERE DISTRICT = 'Kampala'
 ORDER BY FULL_NAME ASC;

-- ----------------------------------------------------------------------------
-- 2. AGGREGATE FUNCTIONS + GROUP BY + HAVING
-- Total amount saved per member, but only for members who saved MORE THAN
-- 5,000,000 UGX. The HAVING clause filters groups after aggregation.
-- ----------------------------------------------------------------------------
PROMPT -- 2. GROUP BY + HAVING (groups that saved more than 5M)
SELECT m.FULL_NAME,
       COUNT(s.SAVINGS_ID) AS MONTHS_SAVED,
       NVL(SUM(s.AMOUNT_CONTRIBUTED), 0) AS TOTAL_SAVED
  FROM MEMBER m
  JOIN SAVINGS_RECORD s ON s.MEMBER_ID = m.MEMBER_ID
 GROUP BY m.MEMBER_ID, m.FULL_NAME
HAVING NVL(SUM(s.AMOUNT_CONTRIBUTED), 0) > 5000000
 ORDER BY TOTAL_SAVED DESC;

-- ----------------------------------------------------------------------------
-- 3. JOINS (three tables)
-- Every passport with the member and the current score it was based on.
-- ----------------------------------------------------------------------------
PROMPT -- 3. Three-table INNER JOIN
SELECT p.QR_TOKEN, m.FULL_NAME, m.NIN, s.SCORE_VALUE, s.SCORE_BAND,
       p.PASSPORT_STATUS, p.EXPIRES_AT
  FROM CREDIT_PASSPORT p
  JOIN MEMBER m ON m.MEMBER_ID = p.MEMBER_ID
  JOIN CREDIT_SCORE s ON s.SCORE_ID = p.SCORE_ID
 WHERE p.PASSPORT_STATUS = 'ACTIVE'
 ORDER BY p.EXPIRES_AT ASC;

-- ----------------------------------------------------------------------------
-- 4a. SUBQUERY - scalar subquery
-- Members whose total savings are ABOVE the organisation-wide average.
-- The inner query computes one value used by the outer WHERE.
-- ----------------------------------------------------------------------------
PROMPT -- 4a. Scalar subquery (above-average savers)
SELECT m.FULL_NAME, NVL(SUM(s.AMOUNT_CONTRIBUTED), 0) AS TOTAL_SAVED
  FROM MEMBER m
  JOIN SAVINGS_RECORD s ON s.MEMBER_ID = m.MEMBER_ID
 GROUP BY m.MEMBER_ID, m.FULL_NAME
HAVING NVL(SUM(s.AMOUNT_CONTRIBUTED), 0) >
       (SELECT AVG(AMOUNT_CONTRIBUTED) FROM SAVINGS_RECORD)
 ORDER BY TOTAL_SAVED DESC;

-- ----------------------------------------------------------------------------
-- 4b. SUBQUERY - IN subquery
-- Members who have EVER taken a loan (via a subquery on LOAN_RECORD).
-- ----------------------------------------------------------------------------
PROMPT -- 4b. IN subquery (members who have taken a loan)
SELECT FULL_NAME, PHONE_NUMBER, DISTRICT
  FROM MEMBER
 WHERE MEMBER_ID IN (SELECT DISTINCT MEMBER_ID FROM LOAN_RECORD)
 ORDER BY FULL_NAME;

-- ----------------------------------------------------------------------------
-- 4c. SUBQUERY - correlated subquery
-- Loans that are LARGER than the member's own average loan amount
-- (the inner query is re-evaluated for every outer row).
-- ----------------------------------------------------------------------------
PROMPT -- 4c. Correlated subquery (loans above own average)
SELECT m.FULL_NAME, l.LOAN_AMOUNT, l.LOAN_STATUS
  FROM LOAN_RECORD l
  JOIN MEMBER m ON m.MEMBER_ID = l.MEMBER_ID
 WHERE l.LOAN_AMOUNT >
       (SELECT NVL(AVG(l2.LOAN_AMOUNT), 0)
          FROM LOAN_RECORD l2
         WHERE l2.MEMBER_ID = l.MEMBER_ID)
 ORDER BY m.FULL_NAME;

-- ----------------------------------------------------------------------------
-- 5a. SET OPERATOR - UNION (distinct rows from both queries)
-- Everyone who EITHER has an active passport OR a current score.
-- ----------------------------------------------------------------------------
PROMPT -- 5a. UNION
SELECT MEMBER_ID, 'HAS_ACTIVE_PASSPORT' AS CATEGORY
  FROM CREDIT_PASSPORT WHERE PASSPORT_STATUS = 'ACTIVE'
UNION
SELECT MEMBER_ID, 'HAS_CURRENT_SCORE' AS CATEGORY
  FROM CREDIT_SCORE WHERE IS_CURRENT = 'Y'
ORDER BY MEMBER_ID;

-- ----------------------------------------------------------------------------
-- 5b. SET OPERATOR - INTERSECT (rows in both queries)
-- Members who have BOTH taken a loan AND saved money.
-- ----------------------------------------------------------------------------
PROMPT -- 5b. INTERSECT
SELECT MEMBER_ID FROM LOAN_RECORD
INTERSECT
SELECT MEMBER_ID FROM SAVINGS_RECORD
ORDER BY MEMBER_ID;

-- ----------------------------------------------------------------------------
-- 5c. SET OPERATOR - MINUS (rows in the first but not the second)
-- Members who have a current score but have NEVER generated a passport.
-- ----------------------------------------------------------------------------
PROMPT -- 5c. MINUS
SELECT MEMBER_ID FROM CREDIT_SCORE WHERE IS_CURRENT = 'Y'
MINUS
SELECT MEMBER_ID FROM CREDIT_PASSPORT
ORDER BY MEMBER_ID;

-- ----------------------------------------------------------------------------
-- 6. VIEWS
-- The V_PASSPORT_DETAIL view hides the three-table join from reporting code.
-- ----------------------------------------------------------------------------
PROMPT -- 6. Querying a VIEW
SELECT FULL_NAME, SCORE_BAND, PASSPORT_STATUS
  FROM V_PASSPORT_DETAIL
 WHERE SCORE_BAND = 'EXCELLENT';

-- ----------------------------------------------------------------------------
-- 7. EXPLICIT CURSOR (Part V - cursors, anonymous block)
-- LOOP over every member, printing their name and outstanding ACTIVE loans
-- using an explicit cursor (OPEN / FETCH / CLOSE, %NOTFOUND) and the
-- PKG_SACCOINK.OUTSTANDING_BALANCE function from sql/05_packages.sql.
-- ----------------------------------------------------------------------------
PROMPT -- 7. Explicit cursor demo (anonymous block)
SET SERVEROUTPUT ON
BEGIN
    FOR r IN (SELECT MEMBER_ID, FULL_NAME FROM MEMBER ORDER BY FULL_NAME) LOOP
        DBMS_OUTPUT.PUT_LINE(
            r.FULL_NAME || ' owes ' ||
            TO_CHAR(PKG_SACCOINK.OUTSTANDING_BALANCE(r.MEMBER_ID), 'FM999,999,999')
            || ' UGX on active loans');
    END LOOP;
END;
/

PROMPT ==================== END OF PART IV / V DEMOS ====================
