-- ============================================================================
-- SACCOLink (Simplified Prototype)
-- Schema Definition -- 5 entities
-- Oracle Database 18c XE | Java Swing (JDBC)
-- ============================================================================
-- Entities:
--   1. MEMBER          - registered member (NIN anchored)
--   2. LOAN_RECORD     - loan history per member
--   3. SAVINGS_RECORD  - monthly savings per member
--   4. CREDIT_SCORE    - computed score per member
--   5. CREDIT_PASSPORT - time-limited shareable credit summary
--
-- Primary keys are NUMBER columns populated by sequences + BEFORE INSERT
-- triggers (see sql/04_triggers.sql). This is the classic Oracle pattern:
-- no GENERATED BY DEFAULT AS IDENTITY columns.
-- ============================================================================

-- Tolerant "drop everything owned by this schema" block, so the combined
-- install script runs cleanly on a brand-new (empty) Oracle XE schema too.
DECLARE
    TYPE t_names IS TABLE OF VARCHAR2(128);
    TYPE t_obj  IS RECORD (nm VARCHAR2(128), tp VARCHAR2(30));
    TYPE t_objs IS TABLE OF t_obj;
    v_items t_names;
    v_objs  t_objs;
BEGIN
    SELECT table_name   BULK COLLECT INTO v_items FROM user_tables;
    FOR i IN 1 .. v_items.COUNT LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || v_items(i) || '" CASCADE CONSTRAINTS';
    END LOOP;
    SELECT sequence_name BULK COLLECT INTO v_items FROM user_sequences
     WHERE sequence_name NOT LIKE 'ISEQ$$%';   -- system-generated, undroppable
    FOR i IN 1 .. v_items.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP SEQUENCE "' || v_items(i) || '"';
        EXCEPTION
            WHEN OTHERS THEN NULL;
        END;
    END LOOP;
    SELECT view_name    BULK COLLECT INTO v_items FROM user_views;
    FOR i IN 1 .. v_items.COUNT LOOP
        EXECUTE IMMEDIATE 'DROP VIEW "' || v_items(i) || '"';
    END LOOP;
    SELECT synonym_name BULK COLLECT INTO v_items FROM user_synonyms;
    FOR i IN 1 .. v_items.COUNT LOOP
        EXECUTE IMMEDIATE 'DROP SYNONYM "' || v_items(i) || '"';
    END LOOP;
    SELECT object_name, object_type BULK COLLECT INTO v_objs
      FROM user_objects
     WHERE object_type IN ('PACKAGE', 'PACKAGE BODY', 'PROCEDURE', 'FUNCTION');
    FOR i IN 1 .. v_objs.COUNT LOOP
        BEGIN
            EXECUTE IMMEDIATE 'DROP ' || v_objs(i).tp || ' "' || v_objs(i).nm || '"';
        EXCEPTION
            WHEN OTHERS THEN NULL;  -- body may already be dropped with its package
        END;
    END LOOP;
END;
/

-- ----------------------------------------------------------------------------
-- Sequences (consumed by the BEFORE INSERT triggers in 04_triggers.sql)
-- ----------------------------------------------------------------------------
CREATE SEQUENCE SEQ_MEMBER   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOAN     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SAVINGS  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SCORE    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PASSPORT START WITH 1 INCREMENT BY 1 NOCACHE;

-- ----------------------------------------------------------------------------
-- 1. MEMBER
-- ----------------------------------------------------------------------------
CREATE TABLE MEMBER (
    MEMBER_ID       NUMBER       NOT NULL
                    CONSTRAINT PK_MEMBER PRIMARY KEY,
    NIN             VARCHAR2(14) NOT NULL
                    CONSTRAINT UQ_MEMBER_NIN UNIQUE,
    FULL_NAME       VARCHAR2(200) NOT NULL,
    PHONE_NUMBER    VARCHAR2(15)  NOT NULL
                    CONSTRAINT UQ_MEMBER_PHONE UNIQUE,
    DISTRICT        VARCHAR2(100) NOT NULL,
    CONSENT_GIVEN   CHAR(1)       DEFAULT 'N'
                    CONSTRAINT CK_MEMBER_CONSENT CHECK (CONSENT_GIVEN IN ('Y','N')),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_MEMBER_NIN
        CHECK (REGEXP_LIKE(NIN, '^[A-Z0-9]{14}$'))
);

-- ----------------------------------------------------------------------------
-- 2. LOAN_RECORD
-- ----------------------------------------------------------------------------
CREATE TABLE LOAN_RECORD (
    LOAN_ID           NUMBER       NOT NULL
                      CONSTRAINT PK_LOAN PRIMARY KEY,
    MEMBER_ID         NUMBER       NOT NULL
                      CONSTRAINT FK_LOAN_MEMBER REFERENCES MEMBER(MEMBER_ID),
    LOAN_AMOUNT       NUMBER(15,2) NOT NULL,
    DISBURSEMENT_DATE DATE         NOT NULL,
    REPAYMENT_DATE    DATE,
    LOAN_STATUS       VARCHAR2(20) NOT NULL
                      CONSTRAINT CK_LOAN_STATUS
                      CHECK (LOAN_STATUS IN ('ACTIVE','REPAID','DEFAULTED'))
);

CREATE INDEX IDX_LOAN_MEMBER ON LOAN_RECORD(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- 3. SAVINGS_RECORD
-- ----------------------------------------------------------------------------
CREATE TABLE SAVINGS_RECORD (
    SAVINGS_ID          NUMBER       NOT NULL
                        CONSTRAINT PK_SAVINGS PRIMARY KEY,
    MEMBER_ID           NUMBER       NOT NULL
                        CONSTRAINT FK_SAVINGS_MEMBER REFERENCES MEMBER(MEMBER_ID),
    CONTRIBUTION_MONTH  DATE         NOT NULL,
    AMOUNT_CONTRIBUTED  NUMBER(12,2) NOT NULL,
    CONSTRAINT CK_SAVINGS_MONTH
        CHECK (CONTRIBUTION_MONTH = TRUNC(CONTRIBUTION_MONTH, 'MM')),
    CONSTRAINT UQ_SAVINGS_MEMBER_MONTH
        UNIQUE (MEMBER_ID, CONTRIBUTION_MONTH)
);

CREATE INDEX IDX_SAVINGS_MEMBER ON SAVINGS_RECORD(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- 4. CREDIT_SCORE
-- ----------------------------------------------------------------------------
CREATE TABLE CREDIT_SCORE (
    SCORE_ID        NUMBER      NOT NULL
                    CONSTRAINT PK_SCORE PRIMARY KEY,
    MEMBER_ID       NUMBER      NOT NULL
                    CONSTRAINT FK_SCORE_MEMBER REFERENCES MEMBER(MEMBER_ID),
    SCORE_VALUE     NUMBER(5,2) NOT NULL
                    CONSTRAINT CK_SCORE_RANGE CHECK (SCORE_VALUE BETWEEN 0 AND 850),
    SCORE_BAND      VARCHAR2(20) NOT NULL
                    CONSTRAINT CK_SCORE_BAND
                    CHECK (SCORE_BAND IN ('EXCELLENT','GOOD','FAIR','THIN')),
    REPAYMENT_SCORE NUMBER(5,2),
    SAVINGS_SCORE   NUMBER(5,2),
    COMPUTED_AT     TIMESTAMP DEFAULT SYSTIMESTAMP,
    IS_CURRENT      CHAR(1)  DEFAULT 'Y'
                    CONSTRAINT CK_SCORE_CURRENT CHECK (IS_CURRENT IN ('Y','N'))
);

CREATE INDEX IDX_SCORE_MEMBER ON CREDIT_SCORE(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- 5. CREDIT_PASSPORT
-- ----------------------------------------------------------------------------
CREATE TABLE CREDIT_PASSPORT (
    PASSPORT_ID     NUMBER      NOT NULL
                    CONSTRAINT PK_PASSPORT PRIMARY KEY,
    MEMBER_ID       NUMBER      NOT NULL
                    CONSTRAINT FK_PASSPORT_MEMBER REFERENCES MEMBER(MEMBER_ID),
    SCORE_ID        NUMBER      NOT NULL
                    CONSTRAINT FK_PASSPORT_SCORE REFERENCES CREDIT_SCORE(SCORE_ID),
    QR_TOKEN        VARCHAR2(64) NOT NULL
                    CONSTRAINT UQ_PASSPORT_TOKEN UNIQUE,
    PASSPORT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
                    CONSTRAINT CK_PASSPORT_STATUS
                    CHECK (PASSPORT_STATUS IN ('ACTIVE','EXPIRED','REVOKED')),
    GENERATED_AT    TIMESTAMP   DEFAULT SYSTIMESTAMP,
    EXPIRES_AT      TIMESTAMP   NOT NULL,
    VIEW_COUNT      NUMBER      DEFAULT 0
);

CREATE INDEX IDX_PASSPORT_MEMBER ON CREDIT_PASSPORT(MEMBER_ID);

-- ----------------------------------------------------------------------------
-- Read-only view for verification reports
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_PASSPORT_DETAIL AS
SELECT p.PASSPORT_ID,
       p.QR_TOKEN,
       p.PASSPORT_STATUS,
       p.GENERATED_AT,
       p.EXPIRES_AT,
       p.VIEW_COUNT,
       m.MEMBER_ID,
       m.FULL_NAME,
       m.NIN,
       m.DISTRICT,
       s.SCORE_VALUE,
       s.SCORE_BAND
  FROM CREDIT_PASSPORT p
  JOIN MEMBER        m ON m.MEMBER_ID = p.MEMBER_ID
  JOIN CREDIT_SCORE  s ON s.SCORE_ID  = p.SCORE_ID;

-- ----------------------------------------------------------------------------
-- Synonyms (aliases so applications can refer to a stable public name and the
-- underlying object can be repointed without changing application code).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE SYNONYM CLIENTS       FOR MEMBER;
CREATE OR REPLACE SYNONYM LOANS         FOR LOAN_RECORD;
CREATE OR REPLACE SYNONYM SAVINGS       FOR SAVINGS_RECORD;
CREATE OR REPLACE SYNONYM MEMBER_DETAIL FOR V_PASSPORT_DETAIL;

PROMPT SACCOLink simplified schema created successfully.
PROMPT Remember: BEFORE INSERT PK triggers live in sql/04_triggers.sql.
