-- ============================================================================
-- SACCOLink (Simplified Prototype)
-- Sample data + demonstration run (extended mock dataset)
-- NOTE: NIN values below are exactly 14 characters (NIRA format), e.g.
--   CM012345678901  =  'C','M' + 12 digits  =  14 characters
--
-- Primary keys are left NULL / unset so the BEFORE INSERT triggers in
-- sql/04_triggers.sql populate them from the SEQ_* sequences.
-- ============================================================================
SET SERVEROUTPUT ON

-- --- Members (7 personas) ---
INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM012345678901', 'Grace Namukasa',  '0772000001', 'Kampala',  'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM112345678902', 'Okello Moses',    '0772000002', 'Gulu',     'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM212345678903', 'Hassan Ssekabira','0772000003', 'Wakiso',   'N');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM312345678904', 'Amina Nakato',    '0772000004', 'Masaka',   'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM412345678905', 'Sarah Kintu',     '0772000005', 'Jinja',    'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM512345678906', 'John Ochieng',    '0772000006', 'Lira',     'Y');

INSERT INTO MEMBER (NIN, FULL_NAME, PHONE_NUMBER, DISTRICT, CONSENT_GIVEN)
VALUES ('CM612345678907', 'Betty Nansubuga', '0772000007', 'Mbarara',  'Y');

COMMIT;

-- --- Loans ---
-- Grace (3 repaid)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2021-03-01', DATE '2022-03-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Grace Namukasa';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1500000, DATE '2022-05-01', DATE '2023-05-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Grace Namukasa';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 3000000, DATE '2023-08-01', DATE '2024-08-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Grace Namukasa';
-- Okello (1 active)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1000000, DATE '2025-01-15', NULL, 'ACTIVE' FROM MEMBER WHERE FULL_NAME='Okello Moses';
-- Hassan (1 repaid + 1 defaulted)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1500000, DATE '2022-01-01', DATE '2022-12-31', 'REPAID' FROM MEMBER WHERE FULL_NAME='Hassan Ssekabira';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2023-06-01', NULL, 'DEFAULTED' FROM MEMBER WHERE FULL_NAME='Hassan Ssekabira';
-- Sarah (2 repaid)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1000000, DATE '2022-02-01', DATE '2023-02-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Sarah Kintu';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 1500000, DATE '2023-10-01', DATE '2024-10-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Sarah Kintu';
-- John (1 repaid + 1 active)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 800000,  DATE '2023-03-01', DATE '2024-03-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='John Ochieng';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2026-01-10', NULL, 'ACTIVE' FROM MEMBER WHERE FULL_NAME='John Ochieng';
-- Betty (3 repaid)
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 2000000, DATE '2020-01-01', DATE '2021-01-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Betty Nansubuga';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 3000000, DATE '2021-06-01', DATE '2022-06-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Betty Nansubuga';
INSERT INTO LOAN_RECORD (MEMBER_ID, LOAN_AMOUNT, DISBURSEMENT_DATE, REPAYMENT_DATE, LOAN_STATUS)
SELECT MEMBER_ID, 4000000, DATE '2022-09-01', DATE '2023-09-01', 'REPAID' FROM MEMBER WHERE FULL_NAME='Betty Nansubuga';

-- --- Savings (217 monthly entries) ---
BEGIN
    -- Grace: 60 months @ 400,000
    FOR i IN 0 .. 59 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2021-01-01', i), 400000
          FROM MEMBER WHERE FULL_NAME = 'Grace Namukasa';
    END LOOP;
    -- Okello: 24 months @ 50,000
    FOR i IN 0 .. 23 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2023-08-01', i), 50000
          FROM MEMBER WHERE FULL_NAME = 'Okello Moses';
    END LOOP;
    -- Hassan: 30 months @ 200,000
    FOR i IN 0 .. 29 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2022-07-01', i), 200000
          FROM MEMBER WHERE FULL_NAME = 'Hassan Ssekabira';
    END LOOP;
    -- Amina: 1 month @ 100,000
    INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
    SELECT MEMBER_ID, TRUNC(SYSDATE, 'MM'), 100000
      FROM MEMBER WHERE FULL_NAME = 'Amina Nakato';
    -- Sarah: 36 months @ 150,000
    FOR i IN 0 .. 35 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2023-01-01', i), 150000
          FROM MEMBER WHERE FULL_NAME = 'Sarah Kintu';
    END LOOP;
    -- John: 18 months @ 100,000
    FOR i IN 0 .. 17 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2025-01-01', i), 100000
          FROM MEMBER WHERE FULL_NAME = 'John Ochieng';
    END LOOP;
    -- Betty: 48 months @ 250,000
    FOR i IN 0 .. 47 LOOP
        INSERT INTO SAVINGS_RECORD (MEMBER_ID, CONTRIBUTION_MONTH, AMOUNT_CONTRIBUTED)
        SELECT MEMBER_ID, ADD_MONTHS(DATE '2022-01-01', i), 250000
          FROM MEMBER WHERE FULL_NAME = 'Betty Nansubuga';
    END LOOP;
END;
/

COMMIT;

-- --- Compute scores for everyone ---
BEGIN
    FOR r IN (SELECT MEMBER_ID, FULL_NAME FROM MEMBER) LOOP
        DBMS_OUTPUT.PUT_LINE('Computing score for ' || r.FULL_NAME);
        SP_COMPUTE_SCORE(r.MEMBER_ID);
    END LOOP;
END;
/

-- --- Demo: generate + verify a passport for Grace, generate one for Sarah ---
DECLARE
    v_member_id NUMBER;
    v_pid       NUMBER;
    v_token     VARCHAR2(64);
    v_result    VARCHAR2(20);
    v_name      VARCHAR2(200);
    v_score     NUMBER;
    v_band      VARCHAR2(20);
    v_gen       TIMESTAMP;
    v_exp       TIMESTAMP;
BEGIN
    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'Grace Namukasa';
    SP_GENERATE_PASSPORT(p_member_id   => v_member_id,
                         p_passport_id => v_pid,
                         p_qr_token    => v_token);
    DBMS_OUTPUT.PUT_LINE('Passport ' || v_pid || ' generated, token = ' || v_token);

    v_result := FN_VERIFY_PASSPORT(v_token, v_name, v_score, v_band, v_gen, v_exp);
    DBMS_OUTPUT.PUT_LINE('Verify result: ' || v_result || ' | ' || v_name ||
                         ' | Score: ' || v_score || ' (' || v_band || ')');

    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'Sarah Kintu';
    SP_GENERATE_PASSPORT(p_member_id   => v_member_id,
                         p_passport_id => v_pid,
                         p_qr_token    => v_token);
    DBMS_OUTPUT.PUT_LINE('Passport ' || v_pid || ' generated for Sarah Kintu, token = ' || v_token);
END;
/

-- --- Package demo: member summary via PKG_SACCOINK_REPORT ---
DECLARE
    v_member_id NUMBER;
    v_loans   NUMBER;
    v_savings NUMBER;
    v_score   NUMBER;
    v_band    VARCHAR2(20);
BEGIN
    SELECT MEMBER_ID INTO v_member_id FROM MEMBER WHERE FULL_NAME = 'Grace Namukasa';
    PKG_SACCOINK_REPORT.MEMBER_SUMMARY(v_member_id, v_loans, v_savings, v_score, v_band);
    DBMS_OUTPUT.PUT_LINE('Member ' || v_member_id || ' summary -> loans: ' || v_loans ||
                         ', total savings: ' || v_savings ||
                         ', score: ' || v_score || ' (' || v_band || ')');
END;
/

-- --- Final report queries ---
SELECT m.FULL_NAME, s.SCORE_VALUE, s.SCORE_BAND
  FROM CREDIT_SCORE s JOIN MEMBER m ON m.MEMBER_ID = s.MEMBER_ID
 WHERE s.IS_CURRENT = 'Y'
 ORDER BY s.SCORE_VALUE DESC;

SELECT m.FULL_NAME, COUNT(s.SAVINGS_ID) AS MONTHS_SAVED,
       NVL(SUM(s.AMOUNT_CONTRIBUTED), 0) AS TOTAL_SAVED
  FROM MEMBER m
  LEFT JOIN SAVINGS_RECORD s ON s.MEMBER_ID = m.MEMBER_ID
 GROUP BY m.FULL_NAME, m.MEMBER_ID
 ORDER BY MONTHS_SAVED DESC;

SELECT * FROM V_PASSPORT_DETAIL;

SELECT AUDIT_ID, MEMBER_ID, OLD_CONSENT, NEW_CONSENT, CHANGED_BY, CHANGED_AT
  FROM CONSENT_AUDIT;
