-- ============================================================================
-- SACCOLink (Simplified Prototype)
-- Triggers -- sequence-based primary keys + business rules
-- Run AFTER sql/01_schema.sql (needs the SEQ_* sequences).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- PK auto-increment: BEFORE INSERT populates the NUMBER primary key from the
-- matching sequence, replacing the GENERATED BY DEFAULT AS IDENTITY columns.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_MEMBER_BI
BEFORE INSERT ON MEMBER
FOR EACH ROW
WHEN (NEW.MEMBER_ID IS NULL)
BEGIN
    :NEW.MEMBER_ID := SEQ_MEMBER.NEXTVAL;
END TRG_MEMBER_BI;
/

CREATE OR REPLACE TRIGGER TRG_LOAN_BI
BEFORE INSERT ON LOAN_RECORD
FOR EACH ROW
WHEN (NEW.LOAN_ID IS NULL)
BEGIN
    :NEW.LOAN_ID := SEQ_LOAN.NEXTVAL;
END TRG_LOAN_BI;
/

CREATE OR REPLACE TRIGGER TRG_SAVINGS_BI
BEFORE INSERT ON SAVINGS_RECORD
FOR EACH ROW
WHEN (NEW.SAVINGS_ID IS NULL)
BEGIN
    :NEW.SAVINGS_ID := SEQ_SAVINGS.NEXTVAL;
END TRG_SAVINGS_BI;
/

CREATE OR REPLACE TRIGGER TRG_SCORE_BI
BEFORE INSERT ON CREDIT_SCORE
FOR EACH ROW
WHEN (NEW.SCORE_ID IS NULL)
BEGIN
    :NEW.SCORE_ID := SEQ_SCORE.NEXTVAL;
END TRG_SCORE_BI;
/

-- ----------------------------------------------------------------------------
-- Passport defaults: generate the PK, the QR token and the 72-hour expiry in
-- the trigger so a bare INSERT produces a valid passport (business rule: a
-- passport expires 72 hours after generation).
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_PASSPORT_BI
BEFORE INSERT ON CREDIT_PASSPORT
FOR EACH ROW
BEGIN
    IF :NEW.PASSPORT_ID IS NULL THEN
        :NEW.PASSPORT_ID := SEQ_PASSPORT.NEXTVAL;
    END IF;
    IF :NEW.QR_TOKEN IS NULL THEN
        :NEW.QR_TOKEN := DBMS_RANDOM.STRING('X', 32);
    END IF;
    IF :NEW.EXPIRES_AT IS NULL THEN
        :NEW.EXPIRES_AT := SYSTIMESTAMP + INTERVAL '3' DAY;
    END IF;
    IF :NEW.VIEW_COUNT IS NULL THEN
        :NEW.VIEW_COUNT := 0;
    END IF;
END TRG_PASSPORT_BI;
/

-- ----------------------------------------------------------------------------
-- Audit trigger: log every consent change on MEMBER into a lightweight
-- CONSENT_AUDIT table (DPPA-aware). This is a small, self-contained audit log
-- that does not disturb the core 5-entity design.
-- ----------------------------------------------------------------------------
CREATE TABLE CONSENT_AUDIT (
    AUDIT_ID        NUMBER NOT NULL,
    MEMBER_ID       NUMBER NOT NULL,
    OLD_CONSENT     CHAR(1),
    NEW_CONSENT     CHAR(1),
    CHANGED_BY      VARCHAR2(128) DEFAULT USER,
    CHANGED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CONSENT_AUDIT PRIMARY KEY (AUDIT_ID)
);

CREATE SEQUENCE SEQ_CONSENT_AUDIT START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER TRG_MEMBER_CONSENT_AUDIT
AFTER UPDATE OF CONSENT_GIVEN ON MEMBER
FOR EACH ROW
WHEN (OLD.CONSENT_GIVEN IS NULL OR NEW.CONSENT_GIVEN IS NULL
      OR OLD.CONSENT_GIVEN != NEW.CONSENT_GIVEN)
BEGIN
    INSERT INTO CONSENT_AUDIT (AUDIT_ID, MEMBER_ID, OLD_CONSENT, NEW_CONSENT)
    VALUES (SEQ_CONSENT_AUDIT.NEXTVAL, :NEW.MEMBER_ID,
            :OLD.CONSENT_GIVEN, :NEW.CONSENT_GIVEN);
END TRG_MEMBER_CONSENT_AUDIT;
/

PROMPT SACCOLink triggers created successfully (6 triggers).
